### ISSUE TITLE
Bank range in grouped tracks behaves weird

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#106]
Report from a Push4Bitwig user:

"When there are more then 8 tracks in a group and want to skip to track nine with the arrow keys it doesnt let me go to the next page where 9 is...
If i select track nine with my mouse it selects it of course on push, but if you want to skip with arrow buttons to track 8 it jumps back to 9.
I thought it got maybe something to do with that i vary to much tracks around ...
But when just make a group and put 10 clean tracks it , it happens also here."

I can reproduce this. If e.g. I add 12 tracks to a group and move to the 2nd page (tracks 9-12) the bank range seems to be 5-12. You also notice that when you go back to the 1st page and select track 6. It jumps to the 2nd page.

**Comment by vosc** [comment]
It's two bugs, one in Bitwig and one in the script. The one in Bitwig will be fixed for 1.3.8 RC-2.

In Push, the position observer on the track cursor should not use the position to calculate the start position of the siblings channel bank, because the position is not within the context of the siblings bank.
The siblings channel bank scrolls automatically to make the track visible that was used to create the bank (most likely a cursor track), so you can just remove the position observer and the handler in TrackBankProxy.
