### ISSUE TITLE
checkButtonState interferes with jog wheels; new function isControl should be used to check if a cc is valid and isButton should be used to check if ButtonEvent states apply to a control

### ISSUE THREAD

**Issue by 0tt** [teotigraphix/Framework4Bitwig#128]
checkButtonState sends ButtonEvent.UP after every jogwheel change; it results in values being decreased by 1 after a short delay. Solution: make isButton return false for wheels and add an isControl function for checking if a CC is valid.

**Comment by git-moss** [comment]
The function is correct. If you have CCs not belonging to buttongs, they must not be defined as a button. I guess thats a bug in the Machine4Bitwig script. Please report here: https://github.com/teotigraphix/Maschine4Bitwig/issues
Please not that Mike is no longer supporting the Maschine script due to some unresolved issues with the device, which get not solved by NI.
