### ISSUE TITLE
Track Bank page is not adjusted when track is selected in Mix view

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#251]
If a track is selected in Mix layout and the track is outside of the current page, the page is not adjusted to display the track on the controller. It works fine when you select a track in the Arranger layout.
It happens only with hierarchical banks created with CursorTrack.createSiblingsTrackBank()

Reproduce:
1) Test with Push 1 or 2 (or the simulator)
2) Create more than 8 tracks
3) Switch to Mix layout
4) Click on a track outside of the currently displayed track bank page on Push

Note: The page is also adjusted if you display clips and click on a clip on the track.

**Comment by abique** [comment]
How did you create the track cursor?

**Comment by k0k0c** [comment]
This issue is reproducible with TrackBank created with createSiblingsTrackBank as well as createTrackBank. CursorTrack is created with shouldFollowSelection = True and followCursorTrack is initialized to TrackBank. This reproduced only if the first track selected is on a page number that differs from the page number on which the next track is selected by more than one. 
I illustated this on two screenshot. 

In this screenshot the Inst 26 track is selected and the track bank corresponds to the selected track.
https://snipboard.io/eJSpnd.jpg

Next, I select the Inst 6 track in UI Bitwig. The TrackBank switches to the wrong page.
https://snipboard.io/ielS2E.jpg

Reproduced in Arranger view and Clip view as well.

**Comment by git-moss** [comment]
Further analysis shows that it is necessary to call
            siblingBank.followCursorTrack (cursorTrack);
on the sibling bank as well, which fixes the issue.
That it follows automatically on the arranger tracks list, seems to be the real bug.

**Comment by git-moss** [comment]
Just wasted 2 hours reproducing a bug report by a user until I noticed that this bug already is known...

However, while testing I noticed another issue with the auto-follow of the siblings bank:
If you click inside of a group and the clicked track is e.g. on the 2nd page, only the first page is selected.
In the attached screenshots:
1) The first track is selected
2) The last track in the group is clicked (which is on the 2nd page) -> The first track of the first track is selected.
3) Clicking the previous track in the group fixes it again.

Can be tested with the Push 2 simulator.

![TrackFollowInGroup1](https://user-images.githubusercontent.com/3090132/135680768-05159c44-49d8-49ee-9664-620e2d944056.png)
![TrackFollowInGroup2](https://user-images.githubusercontent.com/3090132/135680771-222786d1-624a-4aaa-bb57-eb63ac310168.png)
![TrackFollowInGroup3](https://user-images.githubusercontent.com/3090132/135680772-51077149-d456-42b7-bc8f-c7fb653f844b.png)
.

**Comment by git-moss** [comment]
#271 is related as well.

**Comment by git-moss** [comment]
Still in 4.3 Beta 4.

**Comment by git-moss** [comment]
Works fine now in 5.0.7!
