### ISSUE TITLE
Bugs related to Browser

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#69]
1) As the name of the categoiy column "Filter_s" is sent instead of "Category"

2) There is no IsSelected flag for the results

3) Cursor Item of columns is not updated if a change happens via the browser GUI

4) CursorBrowserFilterItem.selectNext () / selectPrevious 
  -> The name change but not the selection in the browser
  
5) Problem with separate "Any" selection, should be part of the normal list

6) Device Browsing: Dialog only opens if a device is selected.

**Comment by git-moss** [comment]
1) is fixed in Beta 3

**Comment by vosc** [comment]
2) there is BrowserItem.isSelected() ... or is that not what you mean?

**Comment by vosc** [comment]
3) You mean the isSelected() flag is not updated? Or would you expect the cursor itself moves to the item selected in the GUI? The latter would not make sense IMO, as you can select multiple items. Or am i misunderstanding?

**Comment by vosc** [comment]
4) same as 3) when moving the cursor via the item, it does not select items, this is done via the isSelected() flag instead, so that multi-selections can be handled.

**Comment by vosc** [comment]
5) Bitwig issue ID: FLOAT-9239

**Comment by vosc** [comment]
5) Bitwig issue ID: FLOAT-9240

**Comment by git-moss** [comment]
2) Yes, you are right. Seems I overlooked it.
3) + 4) Multiselect on Hardware controllers does not make much sense (unless it would be specifically designed to do it). However, how would I do multi-select via the API? 
When I call previous/next on e.g. tags the name does update, e.g. to "digital" but it does not receive the "selected" flag.

**Comment by vosc** [comment]
Moving the cursor would not mark the item as selected, it involves multiple steps if you want the single-selection behaviour: 
1. un-selected the currently selected items.
1. moving the cursor.
2. marking the new item as selected using item.isSelected().setValue(true).

I understand that multi-selection does not make too much sense on most controllers, but i'm not sure if we should force single-selection in the controller API, because it's different then from the GUI, and maybe there are some script authors who want to use multi-selection.

But as the functions on the Cursor interface are called "selectNext/selectPrevious", maybe it's good to have those functions really select the next item, because then it's consistent with other cursors. Actually consistency is the key, so i think it makes sense as you suggest. I could then add other functions that only move the cursor without selecting.

**Comment by teotigraphix** [comment]
@vosc  Agreed, I am working on Touch4Bitiwg and Volker you are going to hate the things I will ask for after 1.2 is released. :) 

Multi selection is makes sens on a phone/tablet(in this app).

I really think with Touch4Bitwig, I can exploit the controller API in a really dynamic way, that yes other controllers can't use but imagine the possibilities if you add API that may not be relevant to hardware but is relevant to software.

**Comment by git-moss** [comment]
@vosc The suggested "multiple steps" do not work with the bank concept since a selection might be outside of the current bank window. This might also be a problem for "real" multi-selection.

**Comment by teotigraphix** [comment]
@git-moss Didn't think about the track bank boundaries, true definitely.

**Comment by vosc** [comment]
Ok, i implemented it now as described above, will be in beta-5.

**Comment by git-moss** [comment]
Closing this issue and moved the remaining 6) to a new issue entry: https://github.com/teotigraphix/Framework4Bitwig/issues/77
