### ISSUE TITLE
Direct Parameters contain DeviceOn and Macros

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#89]
Is this intentional? If yes, I don't like it ;-)

**Comment by vosc** [comment]
yes, it was due to a fix for a bug that (i think) you reported, parameter values were send without the IDs, remember? I fixed it so that the IDs are sent as well, would you have preferred not to send the values instead?

If i change it back Nektar will kill me, but i'll speak to them and see what they would actually prefer.

**Comment by git-moss** [comment]
Yes, I would like to have them removed for several reasons:
- They are duplicated
- First page contains: On, then Macro 1 - 7; Macro 8 is on the 2nd page
- There are also some bugs with it, which I did not report since I guessed this to be as not intended: On-State paramter cannot be changed; With 1 device (need to check if important) it contained only 1 page (Macro 8 was missing).

**Comment by git-moss** [comment]
Still in Beta 8. Are they intended to be at the end now (which is not the case) or will they be removed again?

**Comment by git-moss** [comment]
Still in 1.2 and all of the parameters are broken, see https://github.com/teotigraphix/Framework4Bitwig/issues/93

**Comment by vosc** [comment]
Should be fixed in 1.3 RC-2, finally.

**Comment by git-moss** [comment]
Fixed in 1.3 RC2.
